name: ci

on: 
  push:
    branches:
      - master

jobs:
    build:
        name: Setup Golang
        runs-on: ubuntu-latest
        steps:
          - uses: actions/checkout@v2
          - uses: actions/setup-go@v2
            with:
              go-version: '^1.14.0'
          - run: | 
              go version
              make
            
