name: ci

on: 
  push:
      branches:
          - master

jobs:
    build:
        name: Build & Test
        runs-on: ubuntu-latest
        steps:
            - name: Setup Golang, build and test source code
            - uses: actions/checkout@v2
              uses: actions/setup-go@v2
              with:
                go-version: '^1.14.0' # The Go version to download (if necessary) and use.
              uses: go-semantic-release/action@v1
              with:
                github-token: ${{ secrets.GITHUB_TOKEN }} 
                changelog-file: 
              run: | 
                go version
                make
                make test
            
