name: ci

on: 
  push:
    branches:
      - master

jobs:
    build:
        name: Setup Golang, Build Docker Image & Run Unit Tests
        runs-on: ubuntu-latest
        steps:
          - uses: actions/checkout@v2
          - uses: actions/setup-go@v2
            with:
              go-version: '^1.14.0'
          - run: | 
              go version
              make
              make test
    release:
        name: Create a Semantic Release
        runs-on: ubuntu-latest
        needs: build
        steps:
          - uses: actions/checkout@v2
          - uses: go-semantic-release/action@v1
            id: semrel
            with:
              github-token: ${{ secrets.GITHUB_TOKEN }} 
              changelog-file: CHANGELOG.md 
          - run: |
              echo "Semantic Release version ${{ steps.semrel.outputs.version }}"
